### PR TITLE
add output dir option

### PR DESCRIPTION
**Pull request by couchand**
This adds a command-line option to change the target directory for the build.

### CODE REVIEW

**Comment by couchand** [comment]
Ping @mgattozzi, what do you think about this?  Happy to make any requested changes.

**Comment by mgattozzi** [comment]
Hey @couchand this is great. There's nothing wrong with it, I've just been busy with a lot of life things and I've had to declare notification bankruptcy quite a few times. I'm happy to merge this in and push a minor version for you, but I think for now I'll be putting this project in maintenance mode since I'm just too busy to really expand this!

I'll merge this now and release a bumped version a little later today :)

**Comment by couchand** [comment]
I totally get the having too much life to do!  Best of luck to you.

Out of curiosity, do you have a suggestion for where else to go for rust/wasm project defaults?  I guess just following along the discussions on rust-lang-nursery/rust-wasm?

**Comment by mgattozzi** [comment]
@couchand definitely rust-lang-nursery/rust-wasm where I've been doing work with the working group there. I would reccomend using stdweb right now or wasm-pack if you plan on making libs for npm consumption. You can find out more at the working group repo in general. Also I did push a new version if you still want to use this but I don't plan on supporting it anytime soon :)

**Pull request merged**
